name: kd_api_call
description: A composable, multi-platform, Future-based API for HTTP requests.
version: 0.0.3
homepage: https://gitlab.com/kdsutariya3022/api-call-package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^1.0.4
  http: ^0.13.3   
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
