name: kd_api_call
description: A composable, multi-platform, Future-based API for HTTP requests.
version: 0.1.1
author: Krunal Sutariya<kdsutariya3022@gmail.com>
homepage: https://gitlab.com/kdsutariya3022/api-call-package

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^2.3.6
  flutter:
    sdk: flutter
  http: ^0.13.5   
  path: ^1.8.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:    
  
  
